config/routes.rb
PizzaDelivery::Application.routes.draw do

  root to: "driver_shifts#index"
  get "driver_shifts/index"
  resources :driver_shifts

  resources :shifts do
    collection do
      post :update_individual
    end
  end

  resources :errors, only: [:index]

  get 'drivers' => 'drivers#index', as: :drivers
  get 'drivers/new' => 'drivers#new', as: :new_driver
  get 'drivers/:id' => 'drivers#show', as: :driver
  post 'drivers' => 'drivers#create'
  get 'drivers/:id/edit' => 'drivers#edit', as: :edit_driver
  patch 'drivers/:id' => 'drivers#update'

  get 'availabilities' => 'availabilities#index', as: :availabilities
  get 'availabilities/:id' => 'availabilities#show', as: :availability
  delete 'availabilities/:id' => 'availabilities#destroy'

end

app/models/driver_shift.rb
class DriverShift
  include Mongoid::Document
  belongs_to :driver
  belongs_to :shift

  has_many :orders
end

app/controllers/driver_shifts_controller.rb
class DriverShiftsController < ApplicationController
	def index
		# We use an array here to reduce the number of queries presented to the database
		begin
			@shifts = Shift.all.to_a
		rescue Exception => ex
			puts "***** Driver Shift Controller error" + ex.message
			redirect_to errors_path
		end
	end
end

app/views/driver_shifts/index.html.erb
<h3>Mamma Mia Pizza Delivery Schedule</h3>

<table>
	<tr>
		<td>&nbsp;</td>
		<% (0..6).each do |dow| %>
			<th rowspan="2">
				<%= Date::DAYNAMES[dow] %>
			</th>
		<% end %>
	</tr>

	<% # A way to track day by day which shift we're in the middle of rendering
		rendering_shift_for_day = Array.new(7, nil)
		# Now cycle through each hour, and each will become a table row
		Shift.hour_range.each do |h| %>
		<tr>
			<td rowspan="2"><%= hour_friendly(h) %></td>
		</tr>
		<tr>
		<% # Go through each day number of the week, which will make cells in the rows
		if h != Shift.hour_range.last
			(0..6).each do |dow| %>
				<% # During each hour slot, find shifts that are on the same day
				@shifts.each do |s| %>
					<% if s.day_of_week == dow %>
						<% # Say we're done rendering on this day if there was a shift that ends in this exact hour
						rendering_shift_for_day[dow] = nil if rendering_shift_for_day[dow] &&rendering_shift_for_day[dow].end_hour == h %>
						<% # Not yet rendering a shift on this day?
						if !rendering_shift_for_day[dow] %>
							<% # This shift's start hour is now?
							if s.start_hour == h
								# Set that we're now rendering a shift for this day
								rendering_shift_for_day[dow] = s
								# And render an appropriate TD
								%>
								<td class="calUsed" rowspan="<%= (s.end_hour - s.start_hour)*2 %>">
									<% # Find all drivers on this shift
									dr = s.drivers
										if dr.count > 0 %>
										<b>Drivers:</b>	
										<% dr.each do |d| %>
											<br /><%= link_to d.name, edit_driver_path(d) %>
										<% end %>
										<br />
									<% end %>

									<% # Find all available drivers
									ad = s.available_drivers(true)
										if ad.count > 0 %>
										<b>Available drivers:</b>	
										<% ad.each do |d| %>
											<br /><%= link_to d.name, edit_driver_path(id: d._id.split("_")[0]) %>
										<% end %>
									<% end %>
								</td>
							<% else %>
								<td class="calUnused" rowspan="2">&nbsp;</td>
							<% end %>
						<% end %>
					<% end %>
				<% end %>
			<% end %>
		<% else %>
			<td rowspan="2" colspan="7" class="calUnused">&nbsp;</td>
		<% end %>
		</tr>
	<% end %>
	<tr><td>&nbsp;</td></tr>
</table>

<%= link_to "Shifts", shifts_path %>
<%= link_to "Drivers", drivers_path %>