config/routes.rb
PizzaDelivery::Application.routes.draw do

  root to: "driver_shifts#index"
  get "driver_shifts/index"
  resources :driver_shifts

  resources :shifts do
    collection do
      post :update_individual
    end
  end

  resources :errors, only: [:index]

  get 'drivers' => 'drivers#index', as: :drivers
  get 'drivers/new' => 'drivers#new', as: :new_driver
  get 'drivers/:id' => 'drivers#show', as: :driver
  post 'drivers' => 'drivers#create'
  get 'drivers/:id/edit' => 'drivers#edit', as: :edit_driver
  patch 'drivers/:id' => 'drivers#update'

  get 'availabilities' => 'availabilities#index', as: :availabilities
  get 'availabilities/:id' => 'availabilities#show', as: :availability
  delete 'availabilities/:id' => 'availabilities#destroy'

end

app/models/driver.rb
class Driver
  include Mongoid::Document
  include Mongoid::Paperclip

  # Include this after_commit so that paperclip doesn't freak out
	def self.after_commit(*args, &block)
    args.each do |arg|
    case arg[:on]
      when :destroy
        after_destroy &block
      end
    end
  end

  field :name, type: String
  has_mongoid_attached_file :image
  has_many :driver_shifts
  has_many :availabilities
  accepts_nested_attributes_for :availabilities

  # Based on a driver's availability, find the shifts that he or she can work
  def available_shifts
    ret = []
    availabilities.each do |a|
      shift = find_shift(a)
      ret.push shift if shift
    end
    ret
  end

  # Based on a given availability, find any shifts that would match up
  def find_shift(a)
    Shift.each do |s|
      if a.start_hour &&
        a.start_hour <= s.start_hour &&
        a.end_hour >= s.end_hour &&
        a.day_of_week == s.day_of_week
        return s
        break # In case there are multiple availabilities that would match, we only need to represent it once
      end
    end
    nil # No match
  end


  def shifts
    DriverShift.where(driver_id: id).map do |ds|
      ds.shift
    end
  end

  def scheduled_hours
    hours = 0
    self.shifts.each do |s|
      hours += s.end_hour - s.start_hour
    end
    hours
  end

  def shift_ids
    shifts.map(&:id)
  end

  # The destroy_all way -- courtesy of John
  # def shift_ids=(list)
  #   DriverShift.where(driver_id: id).destroy_all
  #   list.each do |shift_id|
  #     unless shift_id.blank?
  #       self.driver_shifts.create(shift_id: shift_id)
  #     end
  #   end
  # end

  # Way that doesn't kill everything, but just adds and removes as necessary
  def shift_ids=(vals)
    my_ds = DriverShift.where(driver_id: self.id).map(&:shift_id)
    vals.each do |s|
      next if s.blank?
      s_id = BSON::ObjectId.from_string(s)
      if my_ds.include?(s_id)
        my_ds.delete(s_id)
      else
        self.driver_shifts.create(shift_id: s_id)
      end
    end
    my_ds.each do |r|
      DriverShift.find_by(driver_id: self.id, shift_id: r).destroy
    end
  end

	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

	def index
		@drivers = Driver.all
	end

	def new
		@driver = Driver.new
		1.times { @driver.availabilities.build }
	end

	def create
		Driver.create(driver_params)
		redirect_to new_driver_path
	end

	def edit
		@driver = Driver.find(params[:id])
		1.times { @driver.availabilities.build }
	end

	def update
#		raise params.require(:driver).inspect
#		raise params.require(:driver).permit(:image).inspect
		d = Driver.find(params[:id])
		d.update(driver_params)
		redirect_to drivers_path
	end

private

	def driver_params
		params.require(:driver).permit(
			:name, :image,
			shift_ids: [],
			availabilities_attributes: [:day_of_week, :start_hour, :end_hour, :id]
		)
	end
end

app/views/drivers/_form.html.erb
<%= form_for @driver do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<%= f.text_field :name %>
	<%= f.file_field :image %>

<hr />
Availability:<br />
  <%= f.fields_for :availabilities do |builder| %>
    <%= render 'layouts/availability', f: builder %>
  <% end %>

  <input type="button" id="btnNewAvail" value="Add Availability" />
<hr />

	<fieldset>
		<legend>Select shifts</legend>
		<%= f.collection_check_boxes :shift_ids, @driver.available_shifts, :id, :to_s	 %>
	</fieldset>

	<%= f.submit %>

<% end %>

<script>
  // Find the last <select> with an ID that starts with "driver_availabilities_attributes_"

  //var s = document.getElementsByTagName("select");
  var s = $("select");
  var lastDASelect;
  var dANum;
  $.each($("select"), function(){
    if(this.id.substring(0,33) == "driver_availabilities_attributes_")
      lastDASelect = this;
  });

  if(lastDASelect != null)
  {
    dANum = lastDASelect.id.substring(33, 999);
    dANum = dANum.substring(0, dANum.indexOf("_"));
  }

  // When someone selects something, if all 3 choices are NULL then do the collapse thing that makes sure only one empty thing is showing.

  $(function(){
    // When the button is clicked, copy the very last one and change out the numbers
    // This should actually happen when the drop-downs for the previous one are changed up
    $("#btnNewAvail").click(function(){
      var lastAvailJQ = $(".edit_driver div").last();
      var lastAvail = lastAvailJQ[0].outerHTML;
      var offset = -1
      // The offset moves along through the string until there aren't any more instances
      while((offset = lastAvail.indexOf("availabilities_attributes", offset + 1)) >= 0)
      {
        // Found a match, go forward until we find the numbers
        var numStart = 0;
        for(; offset < lastAvail.length; ++offset)
          if(lastAvail[offset] >= '0' && lastAvail[offset] <= '9')
          {
            numStart = offset;
            break;
          }
        // Now find the end of the numbers
        for(; offset < lastAvail.length; ++offset)
          if(lastAvail[offset] < '0' || lastAvail[offset] > '9')
          {
            // We've got a number -- let's change it out!
            theNumber = lastAvail.substring(numStart, offset);
            theNumber = parseInt(theNumber) + 2;
            lastAvail = lastAvail.substring(0,numStart) + theNumber +
             lastAvail.substring(offset,999999);
            break;
          }
      }
      lastAvailJQ.after(lastAvail);
    });
  });
</script>

app/views/drivers/edit.html.erb
<h3>Edit driver <%= @driver.name %></h3>

<%= render "form" %>

<%= link_to "All Drivers", drivers_path %>
<%= link_to "Schedule", driver_shifts_path %>
<%= link_to "Shifts", shifts_path %>

app/views/drivers/index.html.erb
Here's the happy folks who get out their hoopty and deliver some pies:
<br />
<br />
<% @drivers.each do |d| %>
	<%= link_to d.name, edit_driver_path(d) %> 
	<% if d.scheduled_hours > 0 %><b><% end %>
		<%= d.scheduled_hours %> hours<br />
	<% if d.scheduled_hours > 0 %></b><% end %>
	<% if d.image_file_size %>
		Image: <%= image_tag d.image.url(:small) %><br />
	<% end %>
<% end %>

<br />
<br />
<%= link_to "Schedule", driver_shifts_path %>
<%= link_to "Shifts", shifts_path %>

<script>

x = [1,3,4];
Array.prototype.average = function(){
	tot= 0.0;
	for(var i=0; i<this.length; ++i)
		tot += this[i];
	return tot / this.length;
}

console.log(x.average());

</script>

app/views/drivers/new.html.erb
<h3>Add a new driver</h3>

<%= render "form" %>