config/routes.rb
PizzaDelivery::Application.routes.draw do

  root to: "driver_shifts#index"
  get "driver_shifts/index"
  resources :driver_shifts

  resources :shifts do
    collection do
      post :update_individual
    end
  end

  resources :errors, only: [:index]

  get 'drivers' => 'drivers#index', as: :drivers
  get 'drivers/new' => 'drivers#new', as: :new_driver
  get 'drivers/:id' => 'drivers#show', as: :driver
  post 'drivers' => 'drivers#create'
  get 'drivers/:id/edit' => 'drivers#edit', as: :edit_driver
  patch 'drivers/:id' => 'drivers#update'

  get 'availabilities' => 'availabilities#index', as: :availabilities
  get 'availabilities/:id' => 'availabilities#show', as: :availability
  delete 'availabilities/:id' => 'availabilities#destroy'

end

app/views/layouts/_availability.html.erb
<div>
	<!-- This can display either a Shift or an Availability -->
	<!-- These three call out to helper methods in application_helper.rb -->
	<div class="availabilityEntry">
		<div class="availabilityDropdowns">
			<%= f.select :day_of_week, day_array(f.object.new_record?), {}, {class: "dayDropDown"} %>
			<%= f.select :start_hour, hour_array(f.object.new_record?) %> -
			<%= f.select :end_hour, hour_array(f.object.new_record?) %>
		</div>
		<% if !f.object.new_record? %>
			<%= link_to "X", availability_path(f.object.id), {method: :delete} %>
		<% end %>
	</div>
	<%#= f.object_name %>
	<%#= f.index %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzaDelivery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>